services:
  bocado-magico:
    build: .
    container_name: bocado_magico_app
    ports:
      - "80:80"
      - "443:443"
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: bocado_tunnel
    command: tunnel --url https://bocado-magico:443 --no-autoupdate --no-tls-verify --protocol http2
    restart: always
    depends_on:
      - bocado-magico